#> ოპერატორი (მეტია ვიდრე)
a, b = 5, 3
print(a > b)          # True
c, d = 10, 20
print(c > d)          # False
e, f = 7.5, 7.0
print(e > f)          # True
g, h = -1, -5
print(g > h)          # True
i, j = 100, 50
print(i > j)          # True
k, l = 0, 0
print(k > l)          # False
m, n = 99, 101
print(m > n)          # False
o, p = 23, 23
print(o > p)          # False
q, r = 56, 55
print(q > r)          # True
s, t = 2.5, 2.6
print(s > t)          # False
#< ოპერატორი (ნაკლებია ვიდრე)
a, b = 5, 10
print(a < b)          # True
c, d = 20, 15
print(c < d)          # False
e, f = -3, 2
print(e < f)          # True
g, h = 8, 8
print(g < h)          # False
i, j = 0, 1
print(i < j)          # True
k, l = 3.3, 3.4
print(k < l)          # True
m, n = 100, 99
print(m < n)          # False
o, p = -100, -50
print(o < p)          # True
q, r = 7, 7.1
print(q < r)          # True
s, t = 15, 15
print(s < t)          # False
#>= ოპერატორი (მეტია ან ტოლია)
a, b = 5, 5
print(a >= b)         # True
c, d = 9, 8
print(c >= d)         # True
e, f = -1, -1
print(e >= f)         # True
g, h = 12, 15
print(g >= h)         # False
i, j = 2, 1
print(i >= j)         # True
k, l = 7.5, 7.5
print(k >= l)         # True
m, n = 3.2, 3.3
print(m >= n)         # False
o, p = -10, -10
print(o >= p)         # True
q, r = 100, 99
print(q >= r)         # True
s, t = 50, 51
print(s >= t)         # False
#<= ოპერატორი (ნაკლებია ან ტოლია)
a, b = 10, 10
print(a <= b)         # True
c, d = 3, 4
print(c <= d)         # True
e, f = 5, 4
print(e <= f)         # False
g, h = -2, -1
print(g <= h)         # True
i, j = 100, 100
print(i <= j)         # True
k, l = 0.5, 0.5
print(k <= l)         # True
m, n = 1.0, 1.1
print(m <= n)         # True
o, p = 25, 24
print(o <= p)         # False
q, r = -10, -10
print(q <= r)         # True
s, t = 3.3, 3.3
print(s <= t)         # True
#!= ოპერატორი (არ არის ტოლი)
a, b = 3, 4
print(a != b)         # True
c, d = 10, 10
print(c != d)         # False
e, f = -1, 0
print(e != f)         # True
g, h = 1.5, 1.5
print(g != h)         # False
i, j = 5, 10
print(i != j)         # True
k, l = 0, 1
print(k != l)         # True
m, n = 100, 100
print(m != n)         # False
o, p = -10, 20
print(o != p)         # True
q, r = 50, 51
print(q != r)         # True
s, t = 7.7, 7.8
print(s != t)         # True
#== ოპერატორი (ტოლია)
a, b = 5, 5
print(a == b)         # True
c, d = -10, -10
print(c == d)         # True
e, f = 7.5, 7.5
print(e == f)         # True
g, h = 3, 4
print(g == h)         # False
i, j = 100, 100
print(i == j)         # True
k, l = 10, 15
print(k == l)         # False
m, n = 0, 0
print(m == n)         # True
o, p = -2, -3
print(o == p)         # False
q, r = 8.0, 8.0
print(q == r)         # True
s, t = 50, 51
print(s == t)         # False


